### PR TITLE
Features/crawler

### PR DESCRIPTION
**Pull request by steffencruz**
Introduces a Markov chain-based framework which enables multi-turn conversation with coherence and continuity between rounds. 

- Adds `TransitionMatrix` which wraps the Markov process
- Adds `ContextChain`

This is still WIP, but has been tested (ad hoc) with Wiki-based tasks

### CODE REVIEW

**Comment by steffencruz** [comment]
[conversation.csv](https://github.com/opentensor/prompting/files/14212422/conversation.csv)

# Examples

## Trial 1 

----- Step 1 (Summarization) -----
title       Gonçalo Cardoso (footballer, born 2000)
topic                                        Career
subtopic                       International career
Name: 0, dtype: object

----- Step 2 (Summarization) -----
title            2020–21 FC Basel season
topic                           Overview
subtopic    Winter break transfer window
Name: 1, dtype: object

----- Step 3 (QA) -----
title       2020–21 Swiss Super League
topic                           Awards
subtopic                 Annual awards
Name: 2, dtype: object

----- Step 4 (QA) -----
title       2004–05 Swiss Super League
topic                         Overview
subtopic                      Overview
Name: 3, dtype: object

----- Step 5 (QA) -----
title                 2004 in association football
topic       Winners of national club championships
subtopic                             South America
Name: 4, dtype: object

----- Step 6 (QA) -----
title       2004 in association football
topic                             Events
subtopic                          Events
Name: 5, dtype: object

----- Step 7 (QA) -----
title       1830s in association football
topic                              Events
subtopic                           Events
Name: 6, dtype: object

----- Step 8 (Summarization) -----
title       1820s in football
topic                  Events
subtopic                 1823
Name: 7, dtype: object

----- Step 9 (QA) -----
title                        1830s
topic       Science and technology
subtopic               Electricity
Name: 8, dtype: object


## Trial 2

----- Step 1 (QA) -----
title        Humpolec
topic       Geography
subtopic    Geography
Name: 9, dtype: object

----- Step 2 (Summarization) -----
title       Havlíčkův Brod
topic              History
subtopic           History
Name: 10, dtype: object

----- Step 3 (Summarization) -----
title       Havlíčkův Brod
topic         Demographics
subtopic           Economy
Name: 11, dtype: object

----- Step 4 (QA) -----
title       Czech Republic national football team
topic                                     History
subtopic                                    2000s
Name: 12, dtype: object

----- Step 5 (QA) -----
title                                        FIFA
topic                                   Structure
subtopic    Video replay and goal-line technology
Name: 13, dtype: object


## Trial 3


----- Step 1 (Summarization) -----
title       Eve's Hangout
topic              Legacy
subtopic           Legacy
Name: 14, dtype: object

----- Step 2 (Summarization) -----
title                 Eve's Hangout
topic       Police raid and closure
subtopic    Police raid and closure
Name: 15, dtype: object


## Trial 4

----- Step 1 (DateQA) -----
title       March_18
topic         Events
subtopic        1852
Name: 16, dtype: object

----- Step 2 (Summarization) -----
title       1852 United States presidential election
topic                               General election
subtopic                                     Records
Name: 17, dtype: object

----- Step 3 (QA) -----
title              1852 United States presidential election
topic                                           Nominations
subtopic    Native American (Know-Nothing) Party nomination
Name: 18, dtype: object

----- Step 4 (QA) -----
title       1852 United States presidential election
topic                               General election
subtopic                                     Results
Name: 19, dtype: object

----- Step 5 (Summarization) -----
title       2020 United States presidential election in De...
topic                                       Primary elections
subtopic                                    Primary elections
Name: 20, dtype: object

----- Step 6 (QA) -----
title                2020 United States presidential election
topic                            <i>Texas v. Pennsylvania</i>
subtopic    Suggestion to have state legislatures choose E...
Name: 21, dtype: object

----- Step 7 (Summarization) -----
title       Timeline of the 2020 United States presidentia...
topic                                            January 2021
subtopic                                         January 2021
Name: 22, dtype: object


## Trial 5

----- Step 1 (QA) -----
title       Battersby railway station
topic                         History
subtopic                      History
Name: 23, dtype: object

----- Step 2 (QA) -----
title       Battersby railway station
topic                        Services
subtopic                     Services
Name: 24, dtype: object

----- Step 3 (Summarization) -----
title       Reddish South railway station
topic                             History
subtopic                          History
Name: 25, dtype: object

----- Step 4 (QA) -----
title       Atherton station
topic                History
subtopic             History
Name: 26, dtype: object

----- Step 5 (QA) -----
title       Southern Pacific Railroad
topic                      Presidents
subtopic                     See also
Name: 27, dtype: object

----- Step 6 (QA) -----
title       Southern Pacific Railroad
topic              Diesel locomotives
subtopic            Notable accidents
Name: 28, dtype: object


## Trial 6

----- Step 1 (Debugging) -----
title                                              lexek/chat
topic                                                    Java
subtopic    src/main/java/lexek/wschat/db/model/form/Usern...
Name: 29, dtype: object

----- Step 2 (Summarization) -----
title                 Final Fantasy
topic       Development and history
subtopic                      Music
Name: 30, dtype: object

----- Step 3 (QA) -----
title       Final Fantasy VI
topic            Development
subtopic            Creation
Name: 31, dtype: object

----- Step 4 (QA) -----
title       Final Fantasy III
topic                    Plot
subtopic                Story
Name: 32, dtype: object

----- Step 5 (Summarization) -----
title       Final Fantasy III
topic                Gameplay
subtopic             Gameplay
Name: 33, dtype: object

----- Step 6 (Summarization) -----
title                         Music of Final Fantasy III
topic       <i>Final Fantasy III Original Soundtrack</i>
subtopic                                          Legacy
Name: 34, dtype: object

----- Step 7 (QA) -----
title       Final Fantasy VII
topic                Synopsis
subtopic       Later releases
Name: 35, dtype: object

----- Step 8 (QA) -----
title       Final Fantasy
topic         Other media
subtopic       Characters
Name: 36, dtype: object

----- Step 9 (QA) -----
title       Gameplay of Final Fantasy
topic         Development and history
subtopic                    Reception
Name: 37, dtype: object

----- Step 10 (Summarization) -----
title                                Eidos Interactive
topic                                          History
subtopic    Parent Eidos taken over by SCi (2005–2009)
Name: 38, dtype: object


## Trial 7

----- Step 1 (Mathematics) -----
title                  misc
topic                  misc
subtopic    signum_function
Name: 39, dtype: object

----- Step 2 (Mathematics) -----
title          algebra
topic          algebra
subtopic    vector_dot
Name: 40, dtype: object

----- Step 3 (Mathematics) -----
title       basic_math
topic       basic_math
subtopic      addition
Name: 41, dtype: object

----- Step 4 (Mathematics) -----
title                misc
topic                misc
subtopic    prime_factors
Name: 42, dtype: object

----- Step 5 (Mathematics) -----
title       computer_science
topic       computer_science
subtopic     modulo_division
Name: 43, dtype: object

----- Step 6 (Mathematics) -----
title                  geometry
topic                  geometry
subtopic    pythagorean_theorem
Name: 44, dtype: object


## Trial 8

----- Step 1 (DateQA) -----
title       June_24
topic        Births
subtopic       1898
Name: 45, dtype: object

----- Step 2 (DateQA) -----
title       July_02
topic        Deaths
subtopic       1864
Name: 46, dtype: object

----- Step 3 (DateQA) -----
title       May_13
topic       Births
subtopic      1972
Name: 47, dtype: object

----- Step 4 (DateQA) -----
title       July_04
topic        Births
subtopic       1960
Name: 48, dtype: object

----- Step 5 (QA) -----
title              Solar eclipse of August 21, 2017
topic                       Views outside of the US
subtopic    Solar eclipses ascending node 2015–2018
Name: 49, dtype: object


## Trial 9

----- Step 1 (Mathematics) -----
title                    geometry
topic                    geometry
subtopic    perimeter_of_polygons
Name: 50, dtype: object

----- Step 2 (Mathematics) -----
title       basic_math
topic       basic_math
subtopic     cube_root
Name: 51, dtype: object

----- Step 3 (Summarization) -----
title       Solid geometry
topic              History
subtopic           History
Name: 52, dtype: object

----- Step 4 (Summarization) -----
title           Euclidean space
topic                Definition
subtopic    Distance and length
Name: 53, dtype: object

----- Step 5 (QA) -----
title       Affine transformation
topic                  Properties
subtopic                   Groups
Name: 54, dtype: object

----- Step 6 (Summarization) -----
title       Real projective space
topic            Basic properties
subtopic             Construction
Name: 55, dtype: object

----- Step 7 (QA) -----
title                Projective space
topic       Projective transformation
subtopic               Classification
Name: 56, dtype: object

----- Step 8 (Summarization) -----
title       Antilinear map
topic            Citations
subtopic        References
Name: 57, dtype: object

----- Step 9 (QA) -----
title       Bijection
topic        Examples
subtopic     Inverses
Name: 58, dtype: object

----- Step 10 (QA) -----
title              Binary relation
topic                     Examples
subtopic    Heterogeneous relation
Name: 59, dtype: object


## Trial 10

----- Step 1 (DateQA) -----
title       December_16
topic            Births
subtopic           1944
Name: 60, dtype: object

----- Step 2 (DateQA) -----
title       January_27
topic           Events
subtopic          1999
Name: 61, dtype: object

----- Step 3 (DateQA) -----
title       September_25
topic             Births
subtopic            1957
Name: 62, dtype: object

----- Step 4 (Summarization) -----
title            1957
topic          Births
subtopic    September
Name: 63, dtype: object

**Comment by steffencruz** [comment]
# Debugging examples after most recent commit

## Trial 1


### Step 1 (**Debugging**)
  - **title**: jgb11/design-patterns-tutorial
  - **topic**: Java
  - **subtopic**: src/main/java/com/jgb/designpatterns/factorymethod/parser/impl/ResponseXMLParser.java

### Step 2 (**QA**)
  - **title**: Java syntax
  - **topic**: java.lang.Throwable
  - **subtopic**: Packages

### Step 3 (**Summarization**)
  - **title**: Java syntax
  - **topic**: Type inference
  - **subtopic**: Comments


## Trial 2


### Step 1 (**Debugging**)
  - **title**: Altoterras/TheHeartOfSourcerer
  - **topic**: C++
  - **subtopic**: game/src/sourcerer/es/EsObjectBox.cpp


## Trial 3


### Step 1 (**Debugging**)
  - **title**: ycabon/presentations
  - **topic**: JavaScript
  - **subtopic**: 2018-user-conference/arcgis-js-api-road-ahead/demos/gamepad/api-snapshot/esri/renderers/smartMapping/creators/support/utils.js

### Step 2 (**QA**)
  - **title**: Futures and promises
  - **topic**: History
  - **subtopic**: History

### Step 3 (**Summarization**)
  - **title**: Dataflow programming
  - **topic**: Languages
  - **subtopic**: Languages


## Trial 4


### Step 1 (**Debugging**)
  - **title**: bamsdev/meanjsstack
  - **topic**: HTML
  - **subtopic**: modules/timetables/client/views/timetable.client.view.html

### Step 2 (**Debugging**)
  - **title**: sunqm/mpi4pyscf
  - **topic**: Python
  - **subtopic**: tests/scf/test_hf.py

### Step 3 (**Summarization**)
  - **title**: History of Python
  - **topic**: Version 3
  - **subtopic**: Version 3

**Comment by p-ferreira** [comment]
Is this PR planned to be in the next release?

**Comment by steffencruz** [comment]
[Tracked experiment](https://wandb.ai/opentensor-dev/alpha-validators/runs/buzxstgj/overview?workspace=user-opentensor-steffen)

**Comment by Hollyqui** [comment]
Closed on request of @steffencruz due to not being relevant anymore

**Pull request closed without merging**
